version: "3.7"

services:
  postgres:
    image: postgres:12.1
    volumes:
      - postgres:/var/lib/postgresql/data/

  app:
    build: .
    command: /bin/sh docker-app-init.sh
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - .:/one_bit_exchange
      - gems:/gems
    depends_on:
      - postgres

volumes:
  postgres:
  gems:
