inherit_from: ../.rubocop.yml

# The describe, context and factorybot methods takes much space, so we want to
# disable that rubocop rule to enforce standard usage.
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'define', 'factory']
